/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.graficacion;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import javax.swing.JPanel;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author krist
 */
public class Rotacion extends javax.swing.JFrame {

    /**
     * Creates new form Rotacion
     */
    int x = 150;
    int y = 150;
    int ancho = 100;
    int alto = 100;
    int giro = 0;

    public Rotacion() {
        this.setContentPane(new Graficos());
        this.setLocationRelativeTo(null);
        initComponents();
        jSpinner1.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                giro = (int) jSpinner1.getValue();
                repaint();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Girar");

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(0, 0, 360, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(323, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(234, Short.MAX_VALUE)
                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rotacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rotacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rotacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rotacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rotacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSpinner jSpinner1;
    // End of variables declaration                   
 public class Graficos extends JPanel {

        @Override
        public void paint(Graphics g) {
            super.paint(g); //To change body of generated methods, choose Tools | Templates.
            Graphics2D g2d = (Graphics2D) g;
            g2d.translate(x, y);
            g2d.rotate(Math.toRadians(giro));
            //TECHO DEL VW
            g2d.setColor(Color.GREEN);
            g2d.fillOval(100, 100, 300, 300);
//PARABRISAS VW
            g2d.setColor(Color.CYAN);
            g2d.fillOval(120, 120, 260, 260);
//COFRE DEL VW
            g2d.setColor(Color.GREEN);
            g2d.fillArc(110, 120, 290, 260, 180, 180);
//SALPICADERA IZQUIERDO VW
            g2d.setColor(Color.GREEN);
            g2d.fillOval(60, 250, 140, 160);
//SALPICADERA DERECHA VW
            g2d.setColor(Color.GREEN);
            g2d.fillOval(300, 250, 140, 160);
//FARO IZQUIERDO VW
            g2d.setColor(Color.YELLOW);
            g2d.fillOval(80, 270, 80, 100);
//SALPICADERA DERECHA VW
            g2d.setColor(Color.YELLOW);
            g2d.fillOval(340, 270, 80, 100);
//DEFENSA VW
            g2d.setColor(Color.GRAY);
            g2d.fillOval(55, 375, 390, 35);
//Placa

            g2d.setColor(Color.white);
            g2d.fillRect(220, 380, 50, 25);
            g2d.setColor(Color.BLACK);
            g2d.drawString("GD82UF", 220, 395);

            g2d.setColor(Color.BLACK);
            g2d.fillRect(100, 400, 30, 30);
            g2d.fillRect(380, 400, 30, 30);
//Retrovisores
            g2d.setColor(Color.green);
            g2d.fillOval(70, 225, 40, 40);
            g2d.setColor(Color.green);
            g2d.fillOval(390, 225, 40, 40);
//Limpiaparabrizas
            g2d.setColor(Color.black);
            g2d.drawLine(280, 250, 220, 170);
            g2d.drawLine(320, 250, 260, 170);
//espejo
            g2d.drawLine(240, 120, 240, 130);
            g2d.drawLine(260, 120, 260, 130);
            g2d.fillRect(230, 130, 40, 10);
        }

    }
}
